import 'dotenv/config'

export const env = {
  DATABASE_NAME: process.env.DATABASE_NAME,
  DATABASE_USER_NAME: process.env.DATABASE_USER_NAME,
  DATABASE_USER_PASSWORD: process.env.DATABASE_USER_PASSWORD,

  LOCAL_DEV_APP_HOST: process.env.LOCAL_DEV_APP_HOST,
  LOCAL_DEV_APP_PORT: process.env.LOCAL_DEV_APP_PORT,

  PRODUCTION_APP_HOST: process.env.PRODUCTION_APP_HOST,
  PRODUCTION_APP_PORT: process.env.PRODUCTION_APP_PORT,
  NODE_ENV: process.env.NODE_ENV,

  JWT_SECRET: process.env.JWT_SECRET,
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
  JWT_COOKIE_EXPIRES_IN: process.env.JWT_COOKIE_EXPIRES_IN,

  DOMAIN_NAME: process.env.DOMAIN_NAME
}
